apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-lens-app-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Gowtham029/kong-lens-deployment.git
    targetRevision: HEAD
    path: apps/kong-lens
  destination: 
    server: https://kubernetes.default.svc
    namespace: kong-lens-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true